# Generated by Django 4.1.7 on 2023-03-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('common_name', models.CharField(max_length=100)),
                ('distribution', models.TextField(max_length=250)),
            ],
        ),
    ]
