# Generated by Django 4.1.7 on 2023-03-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='img_url',
            field=models.TextField(default='http', max_length=250),
            preserve_default=False,
        ),
    ]
