# Generated by Django 4.1.7 on 2023-03-05 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_tag_finch_trackers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finch',
            old_name='trackers',
            new_name='tag',
        ),
    ]
