# Generated by Django 4.1.7 on 2023-03-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_trackers_finch_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='tag',
            field=models.ManyToManyField(blank=True, to='main_app.tag'),
        ),
    ]
